import { Context } from "./BodyTextParagraphComponent";
import React from 'react';
import { fireEvent, render, RenderResult, screen, act } from '@testing-library/react';
import BodyConnectedNodeComponent from "./BodyConnectedNodeComponent";

describe('BodyConnectedNodeComponent', () => {
    test('renders links and fires events on link click', () => {
        const text = `
            hello [world](blah/test test""/another one#anchor)
        `
        let capturedLink = '';
        const component = render(
            <Context.Provider value={{
                currentNodeAnchor: '',
                currentSelectedText: '',
                onLinkClicked: (link) => { capturedLink = link},
                linkRenderer: (link, text) => { return `<a href="${link.split('"').join('&quot;')}">${text}</a>`; }
            }}>
                <BodyConnectedNodeComponent 
                    connectedNodeTitle = 'blah'
                    isAutogenerated = {true}
                  />
            </Context.Provider>
        );
        expect(component.container.innerHTML).toContain("<span class=\"BodyTextParagraphComponent\"><a href=\"blah\">blah</a> autogen</span><");
    });
});