import { MarkdownBodyChunkConnection } from "../md/types";
import React, { useState, useEffect } from 'react';
import BodyTextParagraphComponent from "./BodyTextParagraphComponent";


export default ( { connectedNodeTitle, isAutogenerated }: MarkdownBodyChunkConnection ) => {
    return <div>
        <BodyTextParagraphComponent data={{
            text: `[${connectedNodeTitle}](${connectedNodeTitle}) ${isAutogenerated ? "autogen" : ""}`
        }} inline={true} />
    </div>;
};